version: "3.8"

services:
  tfg-frontend:
    container_name: tfg-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/srv/www/html
    networks:
      - tfg-net

networks:
  tfg-net:
    driver: bridge
